[project]
name = "areyouok-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uvloop~=0.21.0",
    "python-telegram-bot~=21.10",
    "python-telegram-bot[job-queue]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/areyouok_telegram"]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.1",
]