[project]
name = "areyouok-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uvloop~=0.21.0",
    "python-telegram-bot~=21.10",
    "python-telegram-bot[job-queue]",
]

[dependency-groups]
dev = [
    "ruff~=0.12.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-mock>=3.14.0",
    "pytest-cov>=5.0.0",
    "httpx>=0.28.0",
    "factory-boy>=3.3.0",
    "freezegun>=1.5.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/areyouok_telegram"]

[tool.uv]
required-version = "~=0.7.0"

[tool.ruff]
required-version = "~=0.12.0"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "ASYNC",
    "N",
    "UP",
    "YTT",
    "DTZ",
    "A",
    "B",
    "I"
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = true
detect-same-package = true
