name: CI

on:
  push:
  pull_request:
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.20"
    
    - name: Set up Environment
      run: |
        uv sync --locked
    
    - name: Run Linter
      run: |
        uv run --locked ruff check --no-fix .

    - name: Run Formatter
      run: |
        uv run --locked ruff format --check .

    - name: Run Tests (with coverage)
      run: |
        uv run --locked pytest --cov=areyouok_telegram --cov-report=term-missing --cov-fail-under=95 .
