name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - production
          - research
          - internal
      tag:
        description: 'Image tag (only for internal environment)'
        required: false
        type: string
        default: 'latest'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
  cancel-in-progress: true
  
jobs:
  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:    
    - name: Set Image Tag
      id: set-tag
      run: |
        if [[ "${{ inputs.environment }}" == "internal" && "${{ inputs.tag }}" != "" ]]; then
          echo "IMAGE_TAG=${{ inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
        fi
    
    - name: Pull Image
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        envs: GH_PACKAGE_TOKEN,GH_ACTOR,IMAGE_TAG
        script: |
          echo "$GH_PACKAGE_TOKEN" | docker login ghcr.io -u "$GH_ACTOR" --password-stdin
          docker pull ghcr.io/btimothy-har/areyouok-telegram:$IMAGE_TAG
      env:
        GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
        GH_ACTOR: ${{ github.actor }}
        IMAGE_TAG: ${{ steps.set-tag.outputs.IMAGE_TAG }}
    