name: Deploy

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.3
      env:
        GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
        GH_ACTOR: ${{ github.actor }}
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        envs: |
          GH_PACKAGE_TOKEN,
          GITHUB_ACTOR
        script: |
          echo "Logging into GitHub Container Registry..."
          echo "$GH_PACKAGE_TOKEN" | docker login ghcr.io -u "github_user" --password-stdin
          
          echo "Pulling latest Docker image..."
          docker pull ghcr.io/btimothy-har/areyouok-telegram:latest
    